### ISSUE TITLE
Submit plugin to Matrix branch

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-addon-formula1#4]
According to https://forum.kodi.tv/showthread.php?tid=351745, plugins will only be available in Kodi v19 if they

* bump the xbmc.python dependency to 3.0.0 in the addon.xml file
* are re-submitted to the Matrix branch

## TODO

* [x] Create a Krypton branch to be able to backport fixes
* [x] Add a Matrix bagde to the README
* [x] Strip Python 2 compatibility stuff (script.module.future)
* [x] Use new settings format (https://kodi.wiki/view/Add-on_settings_conversion)
* [x] Submit plugin to the Matrix branch
* [ ] Create a new release
